// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCKQKAUyXMCVNx5uawqyw-jouCiB5vJ4U',
    appId: '1:749634279088:web:dbdad3af4c6266b86e4d75',
    messagingSenderId: '749634279088',
    projectId: 'fizjoaktive-8c92d',
    authDomain: 'fizjoaktive-8c92d.firebaseapp.com',
    storageBucket: 'fizjoaktive-8c92d.appspot.com',
    measurementId: 'G-Z14HXYJFRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGuL5yDKoo4J3OyeLjchlnFB7iV6iBz24',
    appId: '1:749634279088:android:5f5417160375dc6a6e4d75',
    messagingSenderId: '749634279088',
    projectId: 'fizjoaktive-8c92d',
    storageBucket: 'fizjoaktive-8c92d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZUUrE8Idh5IJbIhylv-g09gMmb-E0RhI',
    appId: '1:749634279088:ios:5aacb3fbdf407caa6e4d75',
    messagingSenderId: '749634279088',
    projectId: 'fizjoaktive-8c92d',
    storageBucket: 'fizjoaktive-8c92d.appspot.com',
    iosBundleId: 'com.example.fizjoaktive',
  );
}
